version: "3.9"

services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"

  api:
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
      - ./core:/app/core
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - CORS_ORIGINS=["http://localhost:5173"]
