"""Pydantic models for job postings, resumes, and analysis results."""


from pydantic import BaseModel


class JobPosting(BaseModel):
    """Structured job posting data extracted by Firecrawl."""

    title: str
    company: str
    location: str
    salary_range: str | None = None
    job_type: str | None = None
    experience_level: str | None = None
    description: str
    requirements: list[str] = []
    responsibilities: list[str] = []
    benefits: list[str] = []
    application_url: str | None = None
    date_posted: str | None = None


class ScorePenalty(BaseModel):
    """A single scoring penalty or bonus applied during job analysis."""

    rule: str
    points: int
    reason: str


class JobAnalysis(BaseModel):
    """Claude's analysis of job fit against the user's profile."""

    fit_score: int
    fit_reasoning: str
    matching_skills: list[str]
    gaps: list[str]
    keywords: list[str]
    tailoring_strategy: str
    base_score: int | None = None
    penalties: list[ScorePenalty] = []


class ResumeContent(BaseModel):
    """Structured resume content generated by Claude for LaTeX injection."""

    summary: str
    experience: list[dict]
    skills_section: str
    education: list[dict]
    highlighted_projects: list[dict] = []


class CoverLetterContent(BaseModel):
    """Structured cover letter content generated by Claude."""

    greeting: str
    opening_paragraph: str
    body_paragraphs: list[str]
    closing_paragraph: str
    sign_off: str
